### ISSUE TITLE
Harvest error when creator_name and creator_email set

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/metadata-xml#54] opened 2020-04-30 21:15 UTC
Trying to harvest previously working XML files in newer versions of CKAN gave the error:
`Validation Error: {u'Cited-responsible-party': u'Missing value at required subfield Affiliation 1'}`
I eventually tracked it down and found that unsetting the creator_name and creator_email elements in the YAML allowed the resulting XML to be harvested.

**Comment by jeffcullis** [comment] 2020-04-30 21:20
It looks like the presence of contributor_name as well as creator_name causes the creation of two separate citedResponsibleParty elements in the output XML. Not sure if this is what is causing the error however in HNAP it seems this scenario is handled by having a single citedResponsibleParty element that contains both a CI_Individual element as well as a CI_Organization element. For example see the HNAP link for the following dataset:
https://open.canada.ca/data/en/dataset/d744963f-133c-4a50-8329-0b44865c1e3e

**Comment by fostermh** [comment] 2020-05-01 05:48
I believe the validation error is addressed by outstanding pull request https://github.com/cioos-siooc/ckanext-composite/pull/1 and https://github.com/cioos-siooc/cioos-siooc-schema/pull/5

The issue is that one of the individual name or organization name should be set but it is not possible to capture that currently. The alternative is to not require either of them to be set but that seems like a bad idea.

**Comment by jeffcullis** [comment] 2020-05-01 17:02
That definitely looks as though it could address this issue. I've approved those PRs, sorry for the delay they clearly had fallen off my radar unfortunately.

**Comment by n-a-t-e** [comment] 2020-10-01 18:41
I'm gonna assume this issue no longer relevant since switching from acdd type structure. Can reopen if that's not the case

**Closed as completed by n-a-t-e** 2020-10-01 18:41 UTC
